CODEOWNERS
We are public now and I want to have a say about anything that gets merged into `main`.
Use `CODEOWNERS` to enforce that.
=> [Chore] Add CODEOWNERS file

data/domain/account.tsx
Harmless code change testing PR permissions
=> Testing Permissions

data/domain/rift.tsx, pages/_app.tsx, pages/_document.tsx, pages/players.tsx, pages/raw-data.tsx
Working on some bug fixes from the backlog.
* I had a look at the [FOUC issue](https://discord.com/channels/912156088873418792/912646746780348436/1195483474090545202) and tried to resolve it. After trying a bunch of stuff and not getting it to work I realised that it's probably not a FOUC issue. It's more that I'm doing too many client side too early. 
* I'll need to refactor the code to move things like the domain identification further down the stack and get the basic layout fully server side rendered, that should solve those weird flashes (I hope).
*  Finally hide the remaining Zow/Chow maps - latest [Thread](https://discord.com/channels/912156088873418792/912646746780348436/1192727862634102835)
* Make star sign be 1 indexed instead of 0, because why not - …
=> [Work] bug fixes and misc items - Jan 2024

data/domain/equinox.tsx, pages/world-3/equinox.tsx
=> Fixing bar percent calc and added timer till full

data/domain/sigils.tsx
Used wrongly the 63th Vial (shrine charge bonus) instead of the 61th (sigil charge bonus)
=> Use the right Vial bonus

data/domain/breeding.tsx, pages/world-4/breeding.tsx
Added a green border for Shiny bonuses if there is a shiny pet of this type in the fenceyard
=> Updated Shiny bonuses display

components/world-6/sneaking/pristineCharmsSection.tsx, components/world-6/summoning/summoningBattles.tsx, components/world-6/summoning/summoningBonuses.tsx, components/world-6/summoning/summoningUpgrades.tsx, data/domain/anvil.tsx, data/domain/cooking.tsx, data/domain/deathnote.tsx, data/domain/idleonData.tsx, data/domain/sigils.tsx, data/domain/skilling.tsx, data/domain/world-6/sneaking.tsx, data/domain/world-6/summoning.tsx, pages/players.tsx, pages/world-6/sneaking.tsx, pages/world-6/summoning.tsx
Still in progress, made a PR to get more visibilty in case someone wants to help with this
Main goal is to add basic support for Summoning Skill, including : 
- Display Summoning Level
- Display Summoning Essences
- Display Summoning Upgrades (levels, bonus, cost to next level)
- Display Summoning Bonuses
Pristine Charms for Sneaking have been added to the PR as well
=> [Feature] Initial summoning page

data/domain/world-6/sneaking.tsx, data/domain/world-6/summoning.tsx, pages/account/cards.tsx, pages/world-2/alchemy.tsx, pages/world-6/sneaking.tsx
Some bonus qty (lab connection range for example) are stored as strings, so we need to really transform them into Number instead of just using "as number"
=> Fixes bonus increment

data/domain/world-6/summoning.tsx, data/utility.tsx, pages/world-4/breeding.tsx
Kind of same as Cooking, can sort by level, least time to next level, or by bonus
If sorted by bonus, corresponding pets are put in a separated grid at the start of the list
=> Added a sorting Shiny pets functionnality

data/domain/equinox.tsx
Seems like there's a problem for people who bought the Equinox pack, the bonus speed isn't applied, need to investigate further
=> [Fix] Equinox fill rate not accurate

data/domain/alerts.tsx
If the recipe is unlocked (equinox cloud/challenge 16) and we have enough Lucky Lad (75) across the account (so storage + player inventory), display an alert that tells you can craft it
=> [Feature] Luckier Lad alert

pages/players.tsx
- Blood Berserker Zow/Chow page now supports 100M kills for SuperChow (From the vman talent)
- Cleaned up the display of the page a little
- There was an off-by-one issue with how kills were counted: previously it was > 100k/1m/100m, fixed to be >= now
=> [Feature] Added SuperChow support for Blood Berserker

data/domain/account.tsx, data/domain/deathnote.tsx, data/domain/enemies.tsx, pages/world-3/construction.tsx
Added the two new mini-bosses to the miniboss death note and to the dashboard in the minibosses part
=> [Feature] Add new mini boss support

data/utility.tsx
Completely re-wrote the coin mapping logic (based on the wiki) to fix a bug with it.
Source of the steal: https://idleon.wiki/wiki/Module:CoinDisplay
=> [Bugfix] Fix coin array to handle latest coin

app/layout.tsx
I can't serve different files based on the subdomain, so let's try cannonical url.
Some extra robots jazz for fun
=> [Experiment] Cannonical and Robots update

data/domain/data/MarketInfoRepo.ts, data/domain/data/RandoListRepo.ts, data/domain/data/SeedInfoRepo.ts
Just a quick minor update to 2.13 repos, 2.14 weren't done by the wiki bot yet 💀
=> [Update] 2.13

app/layout.tsx
The page isn't showing up in search results, no idea why but might as well fix some tiny bugs.
=> [Bugfix] Minor metadata fixes

data/domain/alerts.tsx
Add 2 new alerts.
One that tells you when you should change the divinity style used in those cases :
- Using TranQi if meditating
- Not using TranQi if not meditating and it's unlocked
- Using a strictly worse style (gives both fewer points and exp) than another unlocked one
One that tells you when you should change the linked divinity based on what the character is doing :
- Linked to Goharut but not in lab
- Linked to Arctis and being in lab
=> [Feature] Addition of 2 new alerts linked to Divinity

data/domain/alerts.tsx, data/domain/idleonData.tsx, data/domain/player.tsx
Wasn't taking into account cases when players are in the lab and linked to Goharut (so counted as meditating while being in the lab)
I also noticed that in some cases the use of if-else to throw alerts wouldn't be accurate (noticed it by being above lv.80 in divinity and using the Mindful style, it was suggesting me to use the Zen style as it wasn't entering the first if but entered the second one) so now use a switch for better results
=> [Bugfix] Divinity Meditation Style Alert

data/domain/alerts.tsx, data/domain/divinity.tsx, data/domain/idleonData.tsx, data/domain/player.tsx
Now include ES special linked God into the check to know if meditating
=> [Fix] Player.meditating check

app/world-6/farming/content.tsx, components/world-6/farming/cropDepot.tsx, components/world-6/farming/landRank.tsx, components/world-6/farming/marketUpgrades.tsx, components/world-6/farming/plots.tsx, components/world-6/sneaking/sneakingInventory.tsx, data/domain/equinox.tsx, data/domain/idleonData.tsx, data/domain/world-2/killroy.tsx, data/domain/world-2/votes.tsx, data/domain/world-6/farming.tsx
This update will aim to make the farming page and bonuses accurate by : 
- Adding new crop names
- Supporting land ranks
- Take into all calculations the new bonus, like achievements, that were added after the page creation
=> [Feature] Update of farming content

data/domain/tome.tsx
Fixed the unlock level of Tome lines
=> [Fix] Tome unlocking level

components/header/dataStatus.tsx, components/login/googleLogin.tsx, data/firebase/data.tsx, lib/stores/appDataStore.tsx
It's very common for users to come to discord to ask questions about infinitely loading page but in reality they are just using the wrong account.
Add explicit handling for missing character names (which is a good indication for missing data) and show a warning on the top right.
Also slightly improved the Google login flow by adding a button for copying the text + opening the google page in one click.
=> [Work] Login enhancements

data/domain/divinity.tsx, data/domain/idleonData.tsx, data/domain/player.tsx, data/domain/world-5/hole/hole.tsx, data/domain/world-5/hole/villager.tsx
Not all the repos are available for us for the hole, so starting off with a few that are.
Currently missing any visuals for hole information or any advanced math.
The only component being handled here is the pocket divinity upgrade and it's impact on the gods players are aligned with.
=> [Feature] The hole - Initial feature support

app/players/content.tsx
Hi! This PR adds an Apocalypse Wow tracker to the Zow/Chow tab. I don't really know what I'm doing so I kinda just copy/pasted until it seemed right, then tested it on my local machine. I'm not seeing any glaring issues, but maybe something outside this file relies on the structure of the file being this way? idk.
=> Apocalypse wow

components/welcome.tsx, components/world-4/breeding/pets.tsx, data/domain/alerts.tsx, data/domain/world-2/votes.tsx, lib/providers/appDataStoreProvider.tsx, lib/stores/appDataStore.tsx
Fixing a few bugs that were reported.
* Parse failure when vote categories are missing.
* Improve error handling on email login failures
* use 2 decimals always for breedability
* Remove Goharut alert as it's useful for sampling
Login code should be completely re-writen, it's a mess
=> [Bugfix] Misc bug fixes work - 11-02-2025

app/login/steam/page.tsx, components/login/steamLogin.tsx, components/welcome.tsx, data/changelog.ts, lib/stores/authStore.tsx, next.config.js
Add support for ugly steam login.
=> [Feature] Steam login

app/players/content.tsx, app/world-1/stamps/content.tsx, app/world-2/arcade/content.tsx, components/base/ItemSourceDisplay.tsx, components/world-1/stampTableView.tsx, data/domain/anvil.tsx, data/domain/arcade.tsx, data/domain/atomCollider.tsx, data/domain/capacity.tsx, data/domain/construction.tsx, data/domain/cooking.tsx, data/domain/idleonData.tsx, data/domain/player.tsx, data/domain/refinery.tsx, data/domain/sailing.tsx, data/domain/sigils.tsx, data/domain/tome.tsx, data/domain/upgradeVault.tsx, data/domain/world-1/stampUpgradeCalculator.ts, data/domain/world-1/stamps.tsx, data/domain/world-6/farming.tsx, data/domain/worship.tsx, lib/grommetTheme.tsx
Experimenting with an alternate view for the stamps page, a data table with filters.
=> [Feature] Stamp grid

data/changelog.ts
=> [Forgot] Change log for Stamp Grid change

app/account/compass/page.tsx, components/account/compassDisplay.tsx, data/changelog.ts, data/domain/arcade.tsx, data/domain/compass.tsx, data/domain/world-6/sneaking.tsx, data/utility.tsx
Few enhancements to the compass feature and fix a bug with missing handling of the premium hat which gives extra dust and also the arcade bonus handling for the new companion and blue balls.
=> [Work] Compass Follow-up

components/navigation.tsx
Fixes #270 
Tested navigation and it is still working. Of course clicking with middle mouse button causes the Next app to reload as we are not using the AppRouter.
---
This pull request refactors and enhances the navigation component in `components/navigation.tsx`. Key changes include introducing a `NavItem` interface for better type safety, refactoring the `OnHoverNav` function to handle mouse events more robustly, and improving the structure of the mobile navigation dropdown. These changes improve code readability, maintainability, and user interaction.
* Introduced a `NavItem` interface to define the structure of navigation items, including optional `subLinks`, improving type safety and clarity (`[components/navigation.tsxL3-R19](diffhunk://#diff-87965675eb054932993012ea135fb551085d338e …
=> Nav items clickable with middle mouse button

app/raw-data/content.tsx
- Fixed the undefined raw data issue when directly going to https://www.idleonefficiency.com/raw-data
- Reduce some nesting
- Improved a bit of the UX
https://github.com/user-attachments/assets/dfd252f7-e8fc-43ce-a92e-bb85cdfc147b
https://github.com/user-attachments/assets/5ac76a5d-e33c-4a61-a0a1-e22b750e3e08
---
This pull request refactors the `RawData` component in `app/raw-data/content.tsx` to improve user experience and handle loading states more effectively. Key changes include the addition of a loading spinner, improved error handling, and updates to the clipboard functionality.
* Added a loading spinner and "Loading data..." message to indicate when data is being fetched (`Spinner` component and `isLoading` state).
* Displayed a "No data available" message when no data is present, …
=> Fix raw data loading issue + Small UX improvements

app/world-5/divinity/content.tsx, components/account/compassDisplay.tsx, components/account/grimoireDisplay.tsx, components/account/shared/EfficiencyUpgradeTable.tsx, components/account/shared/useUpgradeTableData.ts, components/account/tesseractDisplay.tsx, data/changelog.ts, data/domain/compass.tsx, data/domain/divinity.tsx, data/domain/grimoire.tsx, data/domain/tesseract.tsx, data/domain/world-5/hole/hole.tsx
Fixing some bugs!
* Fix filtering on elite class upgrades sometimes showing invalid upgrades.
* Fix max level costs calculations for elite class upgrades.
* Fix bug with pocket divinity.
* Add "Linked Players" display to the gods display in Divinity.
=> [Work] Fix some bugs users reported - September 27th 2025
